server:
  port: 8080

spring:
  profiles:
    active: chainbasetbsc
  datasource:
    url: jdbc:mysql://124.221.134.180:3306/sonarmeta?characterEncoding=utf8
    username: ${mysql.username:root}
    password: ${mysql.password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    root: INFO
    com:
      baomidou:
        mybatisplus: DEBUG
      sonarx:
        sonarmeta:
          mapper: DEBUG
  file:
    path: ./logs

swagger:
  enabled: true
  title: Sonarmeta Demo
  description: Sonarmeta Demo API document Version 2.
  base-package: com.sonarx.sonarmeta.web.controller
  version: 2.0.0

mychain:
  rpc-host: 47.102.104.19
  rpc-port: 18130
  account: hinsliu
  user-password: _Sonarmeta666
  key-password: _Sonarmeta666
  trust-store-password: mychain
  contracts:
    main: 6ab0bb9d64c0972b34472840f28b5fabb0fed1731c0b4006c3fef2d3dbcc103f
    ERC20: 48ca58c75a2fdfffa6af2e58432feb526a787b502da520a96d74ba3fab1bb2a1
    ERC721: a0d64acc2516542b48c670df3509593b234bfc2d020e4fb3e1f9b005bc08b8dd
    ERC998: 2eddecc472becb3d6b3df1a613a87e765a3630ffe3bb0ee934afc049e4c908bd








