server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sonarmeta?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${mysql.username:root}
    password: ${mysql.password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    root: INFO
    com:
      baomidou:
        mybatisplus: DEBUG
      sonarx:
        sonarmeta:
          mapper: DEBUG
  file:
    path: ./logs

swagger:
  enabled: true
  title: Sonarmeta Demo
  description: Sonarmeta Demo API document Version 2.
  base-package: com.sonarx.sonarmeta.web.controller
  version: 2.0.0

web3j:
  rpc:
    localhost: http://localhost:8545
    rinkeby: https://rinkeby.infura.io/v3/
    mainnet: https://mainnet.infura.io/v3/








