server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sonarmeta?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${mysql.username:root}
    password: ${mysql.password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    root: INFO
    com:
      baomidou:
        mybatisplus: DEBUG
      sonarx:
        sonarmeta:
          mapper: DEBUG
  file:
    path: ./logs

swagger:
  enabled: true
  title: Sonarmeta Demo
  description: Sonarmeta Demo API document Version 2.
  base-package: com.sonarx.sonarmeta.web.controller
  version: 2.0.0

web3j:
  rpc:
    localhost: http://localhost:7545
    rinkeby: https://rinkeby.infura.io/v3/
    mainnet: https://mainnet.infura.io/v3/
    chainbase:
      bsc-test: https://bsc-testnet.s.chainbase.online/v1/2DlNmx0PiuN6Ww9iyS1qxY67AmO
      rinkeby: https://ethereum-rinkeby.s.chainbase.online/v1/2Dhf8fn69zor7wXkQU0NxVm8jGq
  #  No '0x' prefix
  contracts:
    main: D4110B84b4f9B14f71c5f1d176D60639AEbb1146
    ERC20: 7BC6312FF95d2827EA8c414B5056434E91b1113f
    ERC721: D274fB777eB9341185660Fd5f0336A8B9f88E9f3
    ERC998: F56a10296BE43aE9409A546754905785b80a5a9F
  accounts-pk:
    controller1: a78dd2aa256882a25fe5b929575f6f70c6e8b1872b22c1925274dee71596d940
    controller2: 8f01ac58c592328b827eeb73a0f024475133088038845a29ac16c31a6c761927









