server:
  port: 8080

spring:
  profiles:
    active: tbsc
  datasource:
    url: jdbc:mysql://124.221.134.180:3306/sonarmeta?characterEncoding=utf8
    username: ${mysql.username:root}
    password: ${mysql.password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    root: INFO
    com:
      baomidou:
        mybatisplus: DEBUG
      sonarx:
        sonarmeta:
          mapper: DEBUG
  file:
    path: ./logs

swagger:
  enabled: true
  title: Sonarmeta Demo
  description: Sonarmeta Demo API document Version 2.
  base-package: com.sonarx.sonarmeta.web.controller
  version: 2.0.0









