# Generated by Django 3.2.9 on 2022-01-15 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sonarmeta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=sonarmeta.models.profile_avatar_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('S', 'secret')], default='S', max_length=1)),
                ('history_flag', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'checking'), ('P', 'passed'), ('F', 'failed')], default='C', max_length=1)),
                ('path', models.FileField(upload_to=sonarmeta.models.resource_file_path)),
                ('type_and_authority', models.CharField(choices=[('O-Pub', 'open-public'), ('C-Pub', 'carry-public'), ('Pri', 'private')], default='O-Pub', max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(max_length=1024)),
                ('category', models.CharField(choices=[('A', 'animals'), ('P', 'plants'), ('C', 'cars')], default='A', max_length=1)),
                ('download_type', models.CharField(choices=[('F', 'free'), ('S', 'sale'), ('N', 'no')], default='F', max_length=1)),
                ('carry', models.BooleanField()),
                ('no_commercial', models.BooleanField()),
                ('entry', models.PositiveIntegerField(blank=True, default=0)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=sonarmeta.models.resource_cover_path)),
                ('sticky_review_id', models.PositiveIntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='ResourceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sonarmeta.profile')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='ResourceReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('at_sign_id', models.PositiveIntegerField(blank=True, null=True)),
                ('at_sign', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='sonarmeta.resourcereview')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='sonarmeta.resourceseries')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='sonarmeta.resourcebranch'),
        ),
        migrations.AddField(
            model_name='resource',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('L', 'like'), ('R', 'reply'), ('S', 'system')], default='L', max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='be_followed', to='sonarmeta.profile')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='sonarmeta.profile')),
            ],
            options={
                'unique_together': {('creator', 'subscriber')},
            },
        ),
        migrations.CreateModel(
            name='UserReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_flag', models.BooleanField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='sonarmeta.resourcereview')),
            ],
            options={
                'unique_together': {('review', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='UserResourceShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='sonarmeta.resource')),
            ],
            options={
                'unique_together': {('resource', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='UserResourceLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='sonarmeta.resource')),
            ],
            options={
                'unique_together': {('resource', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='UserResourceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='sonarmeta.resource')),
            ],
            options={
                'ordering': ['-time'],
                'unique_together': {('resource', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='UserResourceFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='sonarmeta.resource')),
            ],
            options={
                'unique_together': {('resource', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='UserResourceDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='sonarmeta.resource')),
            ],
            options={
                'unique_together': {('resource', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='UserReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_flag', models.BooleanField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='sonarmeta.resourcereply')),
            ],
            options={
                'unique_together': {('reply', 'profile')},
            },
        ),
    ]
