# Generated by Django 3.2.9 on 2022-02-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar_img',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='cover_img',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='oss_path',
            new_name='path',
        ),
    ]
