# Generated by Django 3.2.9 on 2022-02-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0002_auto_20220211_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='carry',
            new_name='no_carry',
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('O', 'original'), ('C', 'carry')], default='O', max_length=1),
        ),
    ]
