# Generated by Django 3.2.9 on 2022-01-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0002_alter_resource_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='type_and_authority',
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('O', 'original'), ('C', 'carry')], default='O', max_length=5),
        ),
    ]
