# Generated by Django 3.2.9 on 2022-02-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0003_auto_20220212_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='sonarmeta-user', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
