# Generated by Django 3.2.9 on 2022-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0005_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='status_change_timestamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
