# Generated by Django 3.2.9 on 2022-02-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0006_resource_status_change_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='path_folder_list',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
