# Generated by Django 3.2.9 on 2022-02-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0007_resource_path_folder_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userresourcefavorite',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='userresourcefavorite',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-12T12:50:44.058694'),
            preserve_default=False,
        ),
    ]
