# Generated by Django 3.2.9 on 2022-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0008_auto_20220219_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscribe',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='usersubscribe',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11T20:28:11.464442'),
            preserve_default=False,
        ),
    ]
