# Generated by Django 3.2.9 on 2022-02-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0009_auto_20220221_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='entry',
        ),
        migrations.CreateModel(
            name='UserResourceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sonarmeta.resource')),
            ],
        ),
    ]
