# Generated by Django 3.2.9 on 2022-02-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0010_auto_20220221_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userresourceentry',
            options={'ordering': ['-time']},
        ),
    ]
