# Generated by Django 3.2.9 on 2022-03-03 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0011_alter_userresourceentry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceBasicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_position_x', models.CharField(max_length=255)),
                ('model_position_y', models.CharField(max_length=255)),
                ('model_position_z', models.CharField(max_length=255)),
                ('model_rotation_x', models.CharField(max_length=255)),
                ('model_rotation_y', models.CharField(max_length=255)),
                ('model_rotation_z', models.CharField(max_length=255)),
                ('camera_position_x', models.CharField(max_length=255)),
                ('camera_position_y', models.CharField(max_length=255)),
                ('camera_position_z', models.CharField(max_length=255)),
                ('camera_rotation_x', models.CharField(max_length=255)),
                ('camera_rotation_y', models.CharField(max_length=255)),
                ('camera_rotation_z', models.CharField(max_length=255)),
                ('fov', models.CharField(max_length=255)),
                ('background_choice', models.CharField(choices=[('颜色', '颜色'), ('图片', '图片'), ('环境', '环境')], default='颜色', max_length=10)),
                ('background_color', models.CharField(blank=True, max_length=10, null=True)),
                ('background_image', models.TextField(blank=True, null=True)),
                ('background_env', models.TextField(blank=True, null=True)),
                ('background_env_brightness', models.CharField(max_length=255)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_settngs', to='sonarmeta.resource')),
            ],
        ),
    ]
