# Generated by Django 3.2.9 on 2022-03-06 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0012_resourcebasicsettings_resourcelightsettings_resourcematerialsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebasicsettings',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_settings', to='sonarmeta.resource'),
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='light_settings', to='sonarmeta.resource'),
        ),
        migrations.AlterField(
            model_name='resourcematerialsettings',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_settings', to='sonarmeta.resource'),
        ),
    ]
