# Generated by Django 3.2.9 on 2022-03-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0013_auto_20220306_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePostProcessingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch', models.BooleanField(default=True)),
                ('ssao_switch', models.BooleanField(default=False)),
                ('ssao_radius', models.CharField(blank=True, max_length=255, null=True)),
                ('ssao_intensity', models.CharField(blank=True, max_length=255, null=True)),
                ('ssao_bias', models.CharField(blank=True, max_length=255, null=True)),
                ('chromatic_aberration_switch', models.BooleanField(default=False)),
                ('chromatic_aberration_offset', models.CharField(blank=True, max_length=255, null=True)),
                ('vignette_switch', models.BooleanField(default=False)),
                ('vignette_offset', models.CharField(blank=True, max_length=255, null=True)),
                ('vignette_darkness', models.CharField(blank=True, max_length=255, null=True)),
                ('bloom_switch', models.BooleanField(default=False)),
                ('bloom_intensity', models.CharField(blank=True, max_length=255, null=True)),
                ('bloom_luminance_threshold', models.CharField(blank=True, max_length=255, null=True)),
                ('bloom_radius', models.CharField(blank=True, max_length=255, null=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_processing_settings', to='sonarmeta.resource')),
            ],
        ),
    ]
