# Generated by Django 3.2.9 on 2022-03-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0014_resourcepostprocessingsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebasicsettings',
            name='camera_rotation_x',
        ),
        migrations.RemoveField(
            model_name='resourcebasicsettings',
            name='camera_rotation_y',
        ),
        migrations.RemoveField(
            model_name='resourcebasicsettings',
            name='camera_rotation_z',
        ),
    ]
