# Generated by Django 3.2.9 on 2022-03-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0015_auto_20220306_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcelightsettings',
            old_name='env_light_switch',
            new_name='env_switch',
        ),
        migrations.AddField(
            model_name='resourcelightsettings',
            name='ambient_directional_light_bias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcelightsettings',
            name='ambient_directional_light_intensity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcelightsettings',
            name='ambient_directional_light_switch',
            field=models.BooleanField(default=True),
        ),
    ]
