# Generated by Django 3.2.9 on 2022-03-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0016_auto_20220306_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcelightsettings',
            old_name='env_orientaion',
            new_name='env_orientation',
        ),
    ]
