# Generated by Django 3.2.9 on 2022-03-16 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0018_resourcematerialsettings_current_pbr_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='branch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='resources', to='sonarmeta.resourcebranch'),
        ),
    ]
