# Generated by Django 3.2.9 on 2022-03-26 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0019_resourcebasicsettings_shading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='path_folder_list',
            new_name='attached',
        ),
    ]
