# Generated by Django 3.2.9 on 2022-03-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0020_rename_path_folder_list_resource_attached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='attached',
            field=models.TextField(blank=True, null=True),
        ),
    ]
