# Generated by Django 3.2.9 on 2022-03-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0021_alter_resource_attached'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='path_folder_list',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
