# Generated by Django 3.2.9 on 2022-03-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0022_resource_path_folder_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcematerialsettings',
            old_name='nodes',
            new_name='textures',
        ),
    ]
