# Generated by Django 3.2.9 on 2022-03-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0023_rename_nodes_resourcematerialsettings_textures'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcematerialsettings',
            name='paramters',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcematerialsettings',
            name='textures',
            field=models.TextField(blank=True, null=True),
        ),
    ]
