# Generated by Django 3.2.9 on 2022-04-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0024_auto_20220331_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('AP', '动物与宠物'), ('A', '建筑'), ('AA', '艺术与抽象'), ('CV', '汽车与交通工具'), ('CC', '人物与生物'), ('CH', '文化遗产与历史'), ('EG', '电子产品与工具'), ('FS', '时尚与风格'), ('FD', '食物与饮料'), ('FH', '家具与家居'), ('M', '音乐'), ('NP', '自然与植物'), ('PT', '地点与旅行'), ('ST', '科学与技术'), ('SF', '运动与健身'), ('WM', '武器与军事')], default='AP', max_length=2),
        ),
    ]
