# Generated by Django 3.2.9 on 2022-04-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0025_alter_resource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebasicsettings',
            name='camera_look_at_x',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcebasicsettings',
            name='camera_look_at_y',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcebasicsettings',
            name='camera_look_at_z',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
