# Generated by Django 3.2.9 on 2022-04-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0027_auto_20220402_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcelightsettings',
            old_name='light_one_attach_to_camera',
            new_name='light_one_attached_to_camera',
        ),
        migrations.RenameField(
            model_name='resourcelightsettings',
            old_name='light_three_attach_to_camera',
            new_name='light_three_attached_to_camera',
        ),
        migrations.RenameField(
            model_name='resourcelightsettings',
            old_name='light_two_attach_to_camera',
            new_name='light_two_attached_to_camera',
        ),
        migrations.AddField(
            model_name='resourcebasicsettings',
            name='near',
            field=models.CharField(default=0.01, max_length=255),
            preserve_default=False,
        ),
    ]
