# Generated by Django 3.2.9 on 2022-04-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0028_auto_20220403_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='ambient_directional_light_bias',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='ambient_directional_light_intensity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='env_brightness',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='env_orientation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_one_angle',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_one_color',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_one_decay',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_one_intensity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_one_penumbra',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_one_position_x',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_one_position_y',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_one_position_z',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_one_shadow_bias',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_three_angle',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_three_color',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_three_decay',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_three_intensity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_three_penumbra',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_three_position_x',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_three_position_y',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_three_position_z',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_three_shadow_bias',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_two_angle',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_two_color',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_two_decay',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_two_intensity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_two_penumbra',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_two_position_x',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_two_position_y',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_two_position_z',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelightsettings',
            name='light_two_shadow_bias',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcepostprocessingsettings',
            name='bloom_intensity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcepostprocessingsettings',
            name='bloom_luminance_threshold',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcepostprocessingsettings',
            name='bloom_radius',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcepostprocessingsettings',
            name='chromatic_aberration_offset',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcepostprocessingsettings',
            name='ssao_bias',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcepostprocessingsettings',
            name='ssao_intensity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcepostprocessingsettings',
            name='ssao_radius',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcepostprocessingsettings',
            name='vignette_darkness',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcepostprocessingsettings',
            name='vignette_offset',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
