# Generated by Django 3.2.9 on 2022-04-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0029_auto_20220404_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebasicsettings',
            name='model_position_x',
        ),
        migrations.RemoveField(
            model_name='resourcebasicsettings',
            name='model_position_y',
        ),
        migrations.RemoveField(
            model_name='resourcebasicsettings',
            name='model_position_z',
        ),
    ]
