# Generated by Django 3.2.9 on 2022-05-07 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0030_auto_20220407_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustommadeDesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['profile'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='wechat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('U', '未发布'), ('C', '审核中'), ('P', '已通过'), ('COU', '订制订单未发布'), ('COC', '订制订单审核中'), ('COP', '订制订单已通过'), ('F', '未通过')], default='U', max_length=10),
        ),
        migrations.AlterField(
            model_name='resourcematerialsettings',
            name='current_pbr_workflow',
            field=models.CharField(choices=[('金属度', '金属度'), ('镜面', '镜面')], default='金属度', max_length=10),
        ),
        migrations.CreateModel(
            name='CustommadeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('images', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('level', models.CharField(choices=[('L', '低'), ('M', '中'), ('H', '高')], default='M', max_length=10)),
                ('status', models.CharField(choices=[('P', '待抢单'), ('P', '进行中'), ('F', '已完成')], default='P', max_length=10)),
                ('attached_files', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('intended_designers', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='CustommadeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('images', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_checked', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('level', models.CharField(choices=[('L', '低'), ('M', '中'), ('H', '高')], default='M', max_length=10)),
                ('status', models.CharField(choices=[('CP', '待签合同'), ('DP', '待付定金'), ('DC', '待验收定金'), ('RP', '待付尾款'), ('RC', '待验收尾款'), ('F', '已完成')], default='CP', max_length=10)),
                ('contract', models.TextField()),
                ('receipt', models.TextField()),
                ('dynamic', models.TextField()),
                ('attached_files', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('ddl_time', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.custommadedesigner')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='custommadedesigner',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sonarmeta.profile'),
        ),
        migrations.AddField(
            model_name='resource',
            name='custommade_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='sonarmeta.custommadeorder'),
        ),
    ]
