# Generated by Django 3.2.9 on 2022-05-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0031_auto_20220507_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommadeorder',
            name='attached_files',
        ),
        migrations.RemoveField(
            model_name='custommaderequirement',
            name='attached_files',
        ),
        migrations.AlterField(
            model_name='custommadeorder',
            name='level',
            field=models.CharField(choices=[('L', '低模'), ('M', '中模'), ('H', '高模')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='custommaderequirement',
            name='level',
            field=models.CharField(choices=[('L', '低模'), ('M', '中模'), ('H', '高模')], default='M', max_length=10),
        ),
    ]
