# Generated by Django 3.2.9 on 2022-05-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0033_threedviewerowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threedviewerowner',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='resource',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
