# Generated by Django 3.2.9 on 2022-05-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0034_auto_20220525_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threedviewerowner',
            old_name='allow_origin',
            new_name='allow_origins',
        ),
        migrations.AddField(
            model_name='threedviewerowner',
            name='top_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
