# Generated by Django 3.2.9 on 2022-05-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0035_auto_20220529_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
