# Generated by Django 3.2.9 on 2022-06-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonarmeta', '0036_profile_available_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threedviewerowner',
            name='retired_time',
            field=models.DateField(),
        ),
    ]
